"""initial relational schema

Revision ID: 4614b9a082eb
Revises: 
Create Date: 2026-07-29 22:39:52.436997
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4614b9a082eb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aircraft_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('iata_code', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('seat_capacity', sa.Integer(), nullable=False),
    sa.CheckConstraint('seat_capacity > 0', name='ck_aircraft_type_capacity_positive'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('iata_code')
    )
    op.create_table('airports',
    sa.Column('iata_code', sa.String(length=3), nullable=False),
    sa.Column('icao_code', sa.String(length=4), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.CheckConstraint('char_length(iata_code) = 3', name='ck_airport_iata_len'),
    sa.CheckConstraint('iata_code = upper(iata_code)', name='ck_airport_iata_upper'),
    sa.PrimaryKeyConstraint('iata_code'),
    sa.UniqueConstraint('icao_code')
    )
    op.create_table('fare_classes',
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('price_multiplier', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('cabin_bag_included', sa.Boolean(), nullable=False),
    sa.Column('checked_bag_included', sa.Boolean(), nullable=False),
    sa.Column('seat_selection_included', sa.Boolean(), nullable=False),
    sa.Column('changeable', sa.Boolean(), nullable=False),
    sa.Column('refundable', sa.Boolean(), nullable=False),
    sa.Column('change_fee_eur', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.CheckConstraint('NOT refundable OR changeable', name='ck_fare_class_refundable_implies_change'),
    sa.CheckConstraint('change_fee_eur >= 0', name='ck_fare_class_change_fee_non_neg'),
    sa.CheckConstraint('price_multiplier > 0', name='ck_fare_class_multiplier_positive'),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('passport_number', sa.String(length=20), nullable=True),
    sa.Column('hashed_password', sa.String(length=128), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_user_email_lower', 'users', [sa.literal_column('lower(email)')], unique=True)
    op.create_index('uq_user_username_lower', 'users', [sa.literal_column('lower(username)')], unique=True)
    op.create_table('aircraft',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('registration', sa.String(length=10), nullable=False),
    sa.Column('aircraft_type_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['aircraft_type_id'], ['aircraft_types.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registration')
    )
    op.create_table('routes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('origin_iata', sa.String(length=3), nullable=False),
    sa.Column('destination_iata', sa.String(length=3), nullable=False),
    sa.Column('distance_km', sa.Integer(), nullable=False),
    sa.Column('scheduled_duration', sa.Interval(), nullable=False),
    sa.CheckConstraint('distance_km > 0', name='ck_route_distance_positive'),
    sa.CheckConstraint('origin_iata <> destination_iata', name='ck_route_origin_ne_destination'),
    sa.ForeignKeyConstraint(['destination_iata'], ['airports.iata_code'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['origin_iata'], ['airports.iata_code'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('origin_iata', 'destination_iata', name='uq_route_od')
    )
    op.create_table('seat_map_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('aircraft_type_id', sa.UUID(), nullable=False),
    sa.Column('seat_number', sa.String(length=4), nullable=False),
    sa.Column('row', sa.Integer(), nullable=False),
    sa.Column('column', sa.String(length=1), nullable=False),
    sa.Column('is_window', sa.Boolean(), nullable=False),
    sa.Column('is_aisle', sa.Boolean(), nullable=False),
    sa.Column('is_exit_row', sa.Boolean(), nullable=False),
    sa.CheckConstraint('NOT (is_window AND is_aisle)', name='ck_seat_map_window_xor_aisle'),
    sa.CheckConstraint('row > 0', name='ck_seat_map_row_positive'),
    sa.ForeignKeyConstraint(['aircraft_type_id'], ['aircraft_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aircraft_type_id', 'seat_number', name='uq_seat_map_seat')
    )
    op.create_table('flights',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('flight_number', sa.String(length=7), nullable=False),
    sa.Column('route_id', sa.UUID(), nullable=False),
    sa.Column('aircraft_id', sa.UUID(), nullable=False),
    sa.Column('departure_date', sa.Date(), nullable=False),
    sa.Column('scheduled_departure', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scheduled_arrival', sa.DateTime(timezone=True), nullable=False),
    sa.Column('base_fare_eur', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'DEPARTED', 'CANCELLED', name='flight_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('base_fare_eur > 0', name='ck_flight_fare_positive'),
    sa.CheckConstraint('scheduled_arrival > scheduled_departure', name='ck_flight_arrival_after_dep'),
    sa.ForeignKeyConstraint(['aircraft_id'], ['aircraft.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('flight_number', 'departure_date', name='uq_flight_number_date')
    )
    op.create_index('ix_flight_departure_date', 'flights', ['departure_date'], unique=False)
    op.create_index('ix_flight_route_date', 'flights', ['route_id', 'departure_date'], unique=False)
    op.create_table('bookings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('booking_reference', sa.String(length=6), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('flight_id', sa.UUID(), nullable=False),
    sa.Column('fare_class_code', sa.String(length=16), nullable=False),
    sa.Column('passenger_full_name', sa.String(length=120), nullable=False),
    sa.Column('passenger_passport', sa.String(length=20), nullable=False),
    sa.Column('card_last4', sa.String(length=4), nullable=False),
    sa.Column('amount_eur', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('CONFIRMED', 'CANCELLED', name='booking_status'), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status = 'CANCELLED') = (cancelled_at IS NOT NULL)", name='ck_booking_cancelled_has_timestamp'),
    sa.CheckConstraint("booking_reference ~ '^[A-Z0-9]{6}$'", name='ck_booking_reference_format'),
    sa.CheckConstraint("card_last4 ~ '^[0-9]{4}$'", name='ck_booking_card_last4_digits'),
    sa.CheckConstraint('amount_eur >= 0', name='ck_booking_amount_non_negative'),
    sa.ForeignKeyConstraint(['fare_class_code'], ['fare_classes.code'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_reference')
    )
    op.create_index('ix_booking_flight', 'bookings', ['flight_id'], unique=False)
    op.create_index('ix_booking_user', 'bookings', ['user_id'], unique=False)
    op.create_table('flight_seats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('flight_id', sa.UUID(), nullable=False),
    sa.Column('seat_number', sa.String(length=4), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'HELD', 'BOOKED', name='seat_status'), nullable=False),
    sa.Column('held_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('booking_id', sa.UUID(), nullable=True),
    sa.CheckConstraint("(status = 'BOOKED') = (booking_id IS NOT NULL)", name='ck_flight_seat_booked_has_booking'),
    sa.CheckConstraint("(status = 'HELD') = (held_until IS NOT NULL)", name='ck_flight_seat_held_has_expiry'),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('flight_id', 'seat_number', name='uq_flight_seat')
    )
    op.create_index('ix_flight_seat_flight_status', 'flight_seats', ['flight_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_flight_seat_flight_status', table_name='flight_seats')
    op.drop_table('flight_seats')
    op.drop_index('ix_booking_user', table_name='bookings')
    op.drop_index('ix_booking_flight', table_name='bookings')
    op.drop_table('bookings')
    op.drop_index('ix_flight_route_date', table_name='flights')
    op.drop_index('ix_flight_departure_date', table_name='flights')
    op.drop_table('flights')
    op.drop_table('seat_map_entries')
    op.drop_table('routes')
    op.drop_table('aircraft')
    op.drop_index('uq_user_username_lower', table_name='users')
    op.drop_index('uq_user_email_lower', table_name='users')
    op.drop_table('users')
    op.drop_table('fare_classes')
    op.drop_table('airports')
    op.drop_table('aircraft_types')
    # ### end Alembic commands ###

    # Not generated by autogenerate. PostgreSQL enum types are created
    # implicitly with the columns that use them, but dropping those tables
    # does not drop the types. Without this, `downgrade` leaves them behind
    # and the next `upgrade` fails with "type flight_status already exists" —
    # a rollback that cannot be rolled forward.
    for enum_name in ("seat_status", "booking_status", "flight_status"):
        op.execute(sa.text(f"DROP TYPE IF EXISTS {enum_name}"))
