"""stop accepting cardholder data

Revision ID: 539e47fa08f4
Revises: 4614b9a082eb
Create Date: 2026-08-01 19:39:51.458494
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '539e47fa08f4'
down_revision: Union[str, None] = '4614b9a082eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Autogenerate does not diff CHECK constraints, so the relaxation from
    # "must be four digits" to "null, or four digits" is written by hand.
    op.drop_constraint("ck_booking_card_last4_digits", "bookings", type_="check")
    op.create_check_constraint(
        "ck_booking_card_last4_digits",
        "bookings",
        "card_last4 IS NULL OR card_last4 ~ '^[0-9]{4}$'",
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bookings', 'card_last4',
               existing_type=sa.VARCHAR(length=4),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # Existing rows have NULL card_last4 and cannot satisfy the old NOT NULL
    # constraint, so the downgrade fills them rather than failing.
    op.execute(sa.text("UPDATE bookings SET card_last4 = '0000' WHERE card_last4 IS NULL"))
    op.drop_constraint("ck_booking_card_last4_digits", "bookings", type_="check")
    op.create_check_constraint(
        "ck_booking_card_last4_digits", "bookings", "card_last4 ~ '^[0-9]{4}$'"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bookings', 'card_last4',
               existing_type=sa.VARCHAR(length=4),
               nullable=False)
    # ### end Alembic commands ###
